[package]
name = "guessing_game"
version = "0.1.0"
edition = "2024"

[dependencies]

rand = "0.8.5"



git init
git remote add origin https://github.com/CarlosrC771/rust_guessing_game.git
git add .
git commit -m "Subiendo proyecto Rust inicial"
git branch -M main
git push -u origin main